### ISSUE TITLE
DE gene tutorial link broken

### ISSUE THREAD

**Issue by artemiyhussnain** [University-of-Adelaide-Bx-Masters/BIOTECH-7005-BIOINF-3000#41]
[Week 10 tutorial link ](https://university-of-adelaide-bx-masters.github.io/BIOTECH-7005-BIOINF-3000/DE_gene_tutorial/Tutorial_DE_Genes.html) on [home page](https://myuni.adelaide.edu.au/courses/75178/pages/front-slash-home-page) is broken, gives a 404 file not found error. Might want to let Zhipeng know.

**Comment by dadelson** [comment]
The tute is not finished yet.

David Adelson
Professor and Chair of Bioinformatics and Computational Genetics
Zhendong Professor for the Molecular Basis of Traditional Chinese Medicine
Postgraduate Coordinator (Genetics)
https://scholar.google.com/citations?user=IeHSBpEAAAAJ&hl=en

Room 2.10, Molecular Life Sciences Bldg.
School of Biological Sciences
The University of Adelaide
South Australia, 5005
AUSTRALIA
Ph    : +61 8 8313 7555
Fax   : +61 8 8313 5338

e-mail: ***@***.***
CRICOS Provider Number 00123M
-----------------------------------------------------------
IMPORTANT: This message may contain confidential or legally privileged
information. If you think it was sent to you by mistake, please delete all
copies and advise the sender. For the purposes of the SPAM Act 2003, this
email is authorised by The University of Adelaide.
Think green: read on the screen.

[cid:b2fe5ce7-9bec-4936-9184-8f9a26c374d0]
--------------------------------------------
Q: Why is this email five sentences or less?
A: http://five.sentenc.es
________________________________
From: Art Hussnain ***@***.***>
Sent: Friday, 7 October 2022 12:06
To: University-of-Adelaide-Bx-Masters/BIOTECH-7005-BIOINF-3000 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [University-of-Adelaide-Bx-Masters/BIOTECH-7005-BIOINF-3000] DE gene tutorial link broken (Issue #41)


<https://university-of-adelaide-bx-masters.github.io/BIOTECH-7005-BIOINF-3000/DE_gene_tutorial/Tutorial_DE_Genes.html>

CAUTION: External email. Only click on links or open attachments from trusted senders.

________________________________
Week 10 tutorial link on home page<https://myuni.adelaide.edu.au/courses/75178/pages/front-slash-home-page> is broken, gives a 404 file not found error. Might want to let Zhipeng know.

**Comment by davmlaw** [comment]
Thanks for reporting - I've fixed the link (it's a PDF so only properly works with [http site](https://university-of-adelaide-bx-masters.github.io/BIOTECH-7005-BIOINF-3000/))
